version: 0.2

phases:

  build:
    commands:
      - aws cloudformation validate-template --template-body file://templates/network.yaml

  post_build:
    commands:
      - aws cloudformation deploy \
          --template-file templates/network.yaml \
          --stack-name network-stack \
          --capabilities CAPABILITY_NAMED_IAM