AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager Stack

Parameters:

  DBUsername:
    Type: String
    Default: admin

Resources:

# ====================================================
# RDS SECRET
# ====================================================

  RDSMasterSecret:
    Type: AWS::SecretsManager::Secret

    Properties:

      Name: rds-mysql-master-secret

      Description: RDS MySQL Master Credentials

      GenerateSecretString:

        SecretStringTemplate: !Sub |
          {
            "username":"${DBUsername}"
          }

        GenerateStringKey: password

        PasswordLength: 20

        ExcludeCharacters: '"@/\'

Outputs:

  SecretArn:
    Description: Secret ARN

    Value: !Ref RDSMasterSecret

    Export:
      Name: RDSMasterSecretArn

  SecretName:
    Description: Secret Name

    Value: !Ref RDSMasterSecret

    Export:
      Name: RDSMasterSecretName
